# https://taskfile.dev

version: '3'

tasks:
  venv.create:
    desc: Create virtual environment
    cmds:
      - python -m venv .venv
  venv.activate:
    desc: Activate virtual environment
    cmds:
      - source .venv/bin/activate
  install:
    desc: Install dependencies
    run: once
    cmds:
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
  setup.day:
    desc: Setup for the day
    status:
      - |
        [ -f "{{.NAME}}.ipynb" ]
    cmds:
      - cat template.ipynb | sed "s/<<DAY>>/{{.DAY}}/g" > "{{.NAME}}.ipynb"
      - git add "{{.NAME}}.ipynb"
    vars:
      NAME: "day_{{.DAY}}"
    requires:
      vars: [ DAY ]
  setup.today:
    desc: Setup for today
    cmds:
      - task: setup.day
        vars:
          DAY:
            sh: date "+%d"
  day.run.all:
    desc: Run all days
    cmds:
      - for i in day_*.ipynb; do jupyter execute --inplace $i; done
