# https://taskfile.dev

version: '3'

tasks:
  venv.create:
    desc: Create virtual environment
    cmds:
      - python -m venv .venv
  install:
    desc: Install dependencies
    run: once
    cmds:
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
  setup.day:
    desc: Setup for the day
    status:
      - |
        [ -f "{{.NAME}}.ipynb" ]
    cmds:
      - cat template/template.ipynb | sed "s/<<DAY>>/{{.DAY}}/g" > "{{.NAME}}.ipynb"
      - git add "{{.NAME}}.ipynb"
    vars:
      NAME: "day_{{.DAY}}"
    requires:
      vars: [ DAY ]
  setup.today:
    desc: Setup for today
    cmds:
      - task: setup.day
        vars:
          DAY:
            sh: date "+%d"
  overview.update:
    desc: Update overview
    deps:
      - install
    cmds:
      - jupyter execute --inplace overview.ipynb