name: Update Overview Notebook

on:
  schedule:
    - cron: '0 3 * * *' # This will run the workflow every day at 3am
  push:
    branches:
      - master
    paths:
      - '.github/workflows/update-overview.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: false

jobs:
  update-overview:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Execute Jupyter notebook
        run: task overview.update
        env:
          AOC_SESSION: ${{ secrets.AOC_SESSION }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        continue-on-error: true
        id: auto-commit-action
        with:
          commit_message: 'Updating Overview Notebook'
          commit_options: '--no-verify'